### ISSUE TITLE
Status of home-page?

### ISSUE THREAD

**Issue by bergmark** [hspec/HUnit#5]
In the cabal file/on hackage the home page is listed as http://hunit.sourceforge.net/. Is this still correct? I would argue that it would be better to just point to this repository since the current home page barely has any content and does not state when it was last updated.

Additonally sourceforge has become an awful site that has been modifying downloads to insert spyware! uBlock origin also blocks sourceforge URLs by default.

**Comment by sol** [comment]
@bergmark I agree.  Please feel free to open a PR if you want to address this.

**Comment by sol** [comment]
@bergmark Please feel free to upload a new release to Hackage and close this.

**Comment by bergmark** [comment]
Done!
