### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by ivanperez-keera** [hspec/HUnit#58]
Hi. I noticed that this library has not seen releases in years. Is it still maintained? If not, is there a recommendation to use something else?

**Comment by sol** [comment]
This library is stable and mostly used as a building block for other test frameworks such as `hspec`, `test-framwork`,  or `HTF`.  There is also `tasty`, however it does not integrate properly with `HUnit`.

By number of Hackage downloads `hspec` (915) is the most popular option, followed by `tasty` (633), `test-framwork` (171),  and `HTF` (103).

If you want to take a look at Hspec then I recommend the following resources.

**Hspec documentation:**
https://hspec.github.io/

**A minimal example:**
https://github.com/hspec/hspec-example

**A simple project that uses Hspec:**
https://github.com/sol/markdown-unlit
