### ISSUE TITLE
Test suite failure with GHC 8.0.1-rc1

### ISSUE THREAD

**Issue by peti** [hspec/HUnit#7]
Citing from http://hydra.cryp.to/build/1550306/nixlog/1/raw:

~~~~~
### Failure in: 1:2:error
tests/HUnitTestBase.lhs:34
for the reports from a test,
expected: [Start State {path = [], counts = Counts {cases = 1, tried = 0, errors = 0, failures = 0}},Error "error" State {path = [], counts = Counts {cases = 1, tried = 1, errors = 1, failures = 0}}]
 but got: [Start State {path = [], counts = Counts {cases = 1, tried = 0, errors = 0, failures = 0}},Error "error\nCallStack (from ImplicitParams):\n  error, called at tests/HUnitTestExtended.hs:20:40 in main:HUnitTestExtended" State {path = [], counts = Counts {cases = 1, tried = 1, errors = 1, failures = 0}}]
~~~~~

**Comment by sol** [comment]
The test suite needs to be special cased for GHC >= 8, see https://github.com/hspec/HUnit/pull/6#issuecomment-172763605.

Patches welcome!

**Comment by bergmark** [comment]
Noting that this is still an issue.

How should this be solved? Is the callstack likely to change or can we just hard code it without creating too much work for us in the future?

**Comment by sol** [comment]
I would be ok with hard coding it for now.

**Comment by bergmark** [comment]
Great, I'll put it on my todo list.

**Comment by sol** [comment]
This is fixed by now, closing.
